[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solvency_proof = "BWg55qMGUf4RUUiFqGAJKPuwLmLpDQRA4y3US97thnSw"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
