use {
    anchor_lang::{
        solana_program::{instruction::Instruction, pubkey::Pubkey},
        InstructionData, ToAccountMetas,
    },
    litesvm::LiteSVM,
    solana_compute_budget_interface::ComputeBudgetInstruction,
    solana_keypair::Keypair,
    solana_message::{Message, VersionedMessage},
    solana_signer::Signer,
    solana_transaction::versioned::VersionedTransaction,
};

// Verifier program artifacts generated by the gnark/sunspot toolchain.
// circuit.proof = 388-byte Groth16 proof; circuit.pw = 76-byte public witness
// ([2 pub, 0 priv, count 2] header + threshold(32) + commitment(32)).
const VERIFIER_SO: &[u8] = include_bytes!("../../../../circuit/target/circuit.so");
const PROOF: &[u8] = include_bytes!("../../../../circuit/target/circuit.proof");
const PUBLIC_WITNESS: &[u8] = include_bytes!("../../../../circuit/target/circuit.pw");

// Public inputs are the two 32-byte field elements trailing the 12-byte header.
const GNARK_HEADER_LEN: usize = 12;

#[test]
fn test_attest_solvency() {
    let program_id = solvency_proof::id();
    let verifier_id = solvency_proof::constants::VERIFIER_ID;

    let payer = Keypair::new();
    let mut svm = LiteSVM::new();

    // Load our program and the verifier. The verifier .so is loaded at
    // VERIFIER_ID (not its own keypair) to satisfy the `address = VERIFIER_ID`
    // constraint in AttestSolvency.
    let program_bytes = include_bytes!("../../../target/deploy/solvency_proof.so");
    svm.add_program(program_id, program_bytes).unwrap();
    svm.add_program(verifier_id, VERIFIER_SO).unwrap();

    svm.airdrop(&payer.pubkey(), 1_000_000_000).unwrap();

    // Extract threshold + commitment from the generated public witness so the
    // test inputs are guaranteed consistent with the proof.
    let threshold = read_threshold(PUBLIC_WITNESS);
    let commitment = read_commitment(PUBLIC_WITNESS);

    // Derive the solvency attestation PDA (seeds = ["solvency"]).
    let (solvency_pda, _bump) =
        Pubkey::find_program_address(&[solvency_proof::SOLVENCY.as_bytes()], &program_id);

    let accounts = solvency_proof::accounts::AttestSolvency {
        signer: payer.pubkey(),
        solvency: solvency_pda,
        verifier: verifier_id,
        system_program: anchor_lang::system_program::ID,
    };

    let ix_data = solvency_proof::instruction::AttestSolvency {
        proof: PROOF.to_vec(),
        threshold,
        commitment,
    };

    let instruction = Instruction {
        program_id,
        accounts: accounts.to_account_metas(None),
        data: ix_data.data(),
    };

    // Groth16/BN254 pairing verification exceeds the default 200k CU budget;
    // raise it to the per-transaction max (1.4M).
    let compute_budget_ix = ComputeBudgetInstruction::set_compute_unit_limit(1_400_000);

    let blockhash = svm.latest_blockhash();
    let msg = Message::new_with_blockhash(
        &[compute_budget_ix, instruction],
        Some(&payer.pubkey()),
        &blockhash,
    );
    let tx = VersionedTransaction::try_new(VersionedMessage::Legacy(msg), &[&payer]).unwrap();

    let res = svm.send_transaction(tx);
    assert!(res.is_ok(), "attest_solvency failed: {:#?}", res.err());

    // The attestation account should now exist and record a verified proof.
    let account = svm
        .get_account(&solvency_pda)
        .expect("solvency PDA not created");
    let attestation: solvency_proof::SolvencyAttestation =
        anchor_lang::AccountDeserialize::try_deserialize(&mut account.data.as_slice()).unwrap();

    assert!(attestation.verified, "attestation not marked verified");
    assert_eq!(attestation.threshold, threshold);
    assert_eq!(attestation.commitment, commitment);
}

/// input[0] is the threshold, encoded as a 32-byte big-endian field element.
/// We read its low 4 bytes back into a u32.
fn read_threshold(pw: &[u8]) -> u32 {
    let field = &pw[GNARK_HEADER_LEN..GNARK_HEADER_LEN + 32];
    u32::from_be_bytes(field[28..32].try_into().unwrap())
}

/// input[1] is the 32-byte commitment.
fn read_commitment(pw: &[u8]) -> [u8; 32] {
    let start = GNARK_HEADER_LEN + 32;
    pw[start..start + 32].try_into().unwrap()
}
